locators:
  inclusions:
    -
  exclusions:
    -
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: fill
    name: work_email
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: work_email
        index: 0
        uses: -1
      - mode: name
        value: work-email
        index: 0
        uses: -1
      - mode: id
        value: work_email
        index: 0
        uses: -1
      - mode: id
        value: work-email
        index: 0
        uses: -1
      - mode: css
        value: '[aria-label="Work Email"]'
        index: 0
        uses: 1
      - mode: id
        value: WorkEmail
        index: 0
        uses: 0
  - verb: fill
    name: first_name
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: first_name
        index: 0
        uses: 1
      - mode: name
        value: first-name
        index: 0
        uses: 0
      - mode: id
        value: first_name
        index: 0
        uses: 0
      - mode: id
        value: first-name
        index: 0
        uses: 0
      - mode: css
        value: '[aria-label="First Name"]'
        index: 0
        uses: 0
      - mode: id
        value: FirstName
        index: 0
        uses: 0
  - verb: fill
    name: last_name
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: last_name
        index: 0
        uses: 1
      - mode: name
        value: last-name
        index: 0
        uses: 0
      - mode: id
        value: last_name
        index: 0
        uses: 0
      - mode: id
        value: last-name
        index: 0
        uses: 0
      - mode: css
        value: '[aria-label="Last Name"]'
        index: 0
        uses: 0
      - mode: id
        value: LastName
        index: 0
        uses: 0
  - verb: click
    name: sign_up
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Sign Up
        index: 0
        uses: 2
      - mode: text
        value: Sign up
        index: 0
        uses: 0
      - mode: value
        value: Sign Up
        index: 0
        uses: 0
      - mode: value
        value: Sign up
        index: 0
        uses: 0
  - verb: fill
    name: password
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: password
        index: 0
        uses: -1
      - mode: name
        value: password
        index: 0
        uses: -1
      - mode: id
        value: password
        index: 0
        uses: -1
      - mode: id
        value: password
        index: 0
        uses: -1
      - mode: css
        value: '[aria-label="Password"]'
        index: 0
        uses: 1
      - mode: id
        value: Password
        index: 0
        uses: 0
