active_locators:
  - mode: ''
    value: ''
    index: 0
    uses: 0
inactive_locators:
  - mode: ''
    value: ''
    index: 0
    uses: 0
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: fill
    name: work_email
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: work_email
        index: 0
        uses: 0
      - mode: name
        value: work-email
        index: 0
        uses: 0
      - mode: id
        value: work_email
        index: 0
        uses: 0
      - mode: id
        value: work-email
        index: 0
        uses: 0
      - mode: css
        value: '[aria-label="Work Email"]'
        index: 0
        uses: 0
  - verb: fill
    name: first_name
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: first_name
        index: 0
        uses: 1
      - mode: name
        value: first-name
        index: 0
        uses: 0
      - mode: id
        value: first_name
        index: 0
        uses: 0
      - mode: id
        value: first-name
        index: 0
        uses: 0
      - mode: css
        value: '[aria-label="First Name"]'
        index: 0
        uses: 0
  - verb: fill
    name: last_name
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: last_name
        index: 0
        uses: 0
      - mode: name
        value: last-name
        index: 0
        uses: 0
      - mode: id
        value: last_name
        index: 0
        uses: 0
      - mode: id
        value: last-name
        index: 0
        uses: 0
      - mode: css
        value: '[aria-label="Last Name"]'
        index: 0
        uses: 0
  - verb: click
    name: search
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Search
        index: 0
        uses: -1
      - mode: text
        value: Search
        index: 0
        uses: -1
      - mode: value
        value: Search
        index: 0
        uses: -1
      - mode: value
        value: Search
        index: 0
        uses: -1
      - mode: css
        value: data-testid="searchToggler"
        index: 0
        uses: -1
      - mode: css
        value: '[data-testid="searchToggler"]'
        index: 0
        uses: 10
  - verb: fill
    name: search
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: search
        index: 0
        uses: -1
      - mode: name
        value: search
        index: 0
        uses: -1
      - mode: id
        value: search
        index: 0
        uses: -1
      - mode: id
        value: search
        index: 0
        uses: -1
      - mode: css
        value: '[aria-label="Search"]'
        index: 0
        uses: -1
      - mode: id
        value: Search
        index: 0
        uses: -1
      - mode: id
        value: universal-nav-app-search
        index: 0
        uses: 12
  - verb: click
    name: cancel
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Cancel
        index: 0
        uses: -1
      - mode: text
        value: Cancel
        index: 0
        uses: -1
      - mode: value
        value: Cancel
        index: 0
        uses: -1
      - mode: value
        value: Cancel
        index: 0
        uses: -1
      - mode: css
        value: '[aria-label="Close search"]'
        index: 0
        uses: 3
