locators:
  inclusions:
    -
  exclusions:
    -
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: click
    name: try_free
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Try Free
        index: 0
        uses: -1
      - mode: text
        value: Try free
        index: 0
        uses: 1
      - mode: value
        value: Try Free
        index: 0
        uses: 0
      - mode: value
        value: Try free
        index: 0
        uses: 0
