locators:
  inclusions:
    -
  exclusions:
    -
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: fill
    name: email
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: email
        index: 0
        uses: 1
      - mode: name
        value: email
        index: 0
        uses: 0
      - mode: id
        value: email
        index: 0
        uses: 0
      - mode: id
        value: email
        index: 0
        uses: 0
      - mode: css
        value: '[aria-label="Email"]'
        index: 0
        uses: 0
      - mode: id
        value: Email
        index: 0
        uses: 0
  - verb: click
    name: continue
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Continue
        index: 0
        uses: 2
      - mode: text
        value: Continue
        index: 0
        uses: 0
      - mode: value
        value: Continue
        index: 0
        uses: 0
      - mode: value
        value: Continue
        index: 0
        uses: 0
  - verb: fill
    name: password
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: password
        index: 0
        uses: 1
      - mode: name
        value: password
        index: 0
        uses: 0
      - mode: id
        value: password
        index: 0
        uses: 0
      - mode: id
        value: password
        index: 0
        uses: 0
      - mode: css
        value: '[aria-label="Password"]'
        index: 0
        uses: 0
      - mode: id
        value: Password
        index: 0
        uses: 0
